# اسم سير العمل (Workflow) الذي سيظهر في GitHub
name: Java CI for Unit Tests

# الأحداث (Events) التي تشغل سير العمل
on:
  # التشغيل عند الدفع (push) إلى الفرع الرئيسي (main)
  push:
    branches: [ main ]
  # التشغيل عند طلب السحب (pull_request) على الفرع الرئيسي (main)
  pull_request:
    branches: [ main ]
    
# تعريف المهام (Jobs)
jobs:
  # اسم المهمة: build
  build:
    # تحديد المشغل (Runner)
    runs-on: ubuntu-latest
    
    # خطوات (Steps) المهمة
    steps:
    
      # 1. سحب (Checkout) الكود من المستودع 
      - name: Checkout Repository Code
        uses: actions/checkout@v4 

      # 2. إعداد بيئة Java 21
      # يتم استخدام إجراء (Action) جاهز لإعداد Java [cite: 38]
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven # لتخزين تبعيات Maven مؤقتًا

      # 3. تشغيل اختبارات الوحدة (Run Unit Tests) 
      # هذا الأمر يقوم بتشغيل جميع الاختبارات [cite: 11]
      - name: Run Maven Tests
        # الأمر 'mvn test' هو الأمر القياسي لتشغيل الاختبارات في Maven
        run: mvn test 
        
      # (اختياري) يمكن إضافة خطوات أخرى مثل بناء التطبيق كاملاً (package) بعد نجاح الاختبارات
      # - name: Package application
      #   run: mvn -B package --file pom.xml